### PR TITLE
Removed extra quota in docs example

### PR DESCRIPTION
**Pull request by pmokeev**

### CODE REVIEW

**Comment by karenhchu** [comment]
Hey there – looks like you're missing the DCO sign-off. Would you mind updating your commit message per the instructions here? https://github.com/helm/helm-www/pull/1332/checks?check_run_id=7246235881 Thanks!

**Comment by angellk** [comment]
Hi @pmokeev ! Would you still like to submit this? Please reach out if you have any questions re: the DCO sign-off.

**Comment by pmokeev** [comment]
> Would you still like to submit this? Please reach out if you have any questions re: the DCO sign-off.

Sorry for such a delay
Everything seems to be ok now :)

**Review by angellk — APPROVED** [review]
lgtm

**Pull request merged**
