### PR TITLE
Added JFrog Artifactory as OCI supported registry

### PR DESCRIPTION
**Pull request by galzil1**
Signed-off-by: galzil1 <70253799+galzil1@users.noreply.github.com>

### CODE REVIEW

**Review by angellk — CHANGES_REQUESTED** [review]
hi @galzil1 - the list is alphabetical - could you please update to place JFrog after Google?

**Comment by galzil1** [comment]
@angellk thanks, updated per your comment

**Review by angellk — CHANGES_REQUESTED** [review]
thanks @galzil1 ! could you please remove the spacing between bracket and parenthesis?

**Comment by galzil1** [comment]
@angellk done. please review

**Review by angellk — APPROVED** [review]
lgtm - thanks @galzil1 !

**Pull request merged**
