### PR TITLE
Docker Hub has OCI artifact support now

### PR DESCRIPTION
**Pull request by justincormack**
Add link to blog post which has a Helm example.

### CODE REVIEW

**Comment by yxxhero** [comment]
@justincormack oh. this is good news. Thanks very much.

**Review by yxxhero — APPROVED** [review]

**Review by hickeyma — CHANGES_REQUESTED** [review]
Thanks for pushing this @justincormack, its great new on DockerHub OCI support. 

One thing. Can you provide a doc link like the other providers instead of a blog post? Th reason being is we want to provide supported documentation links.

**Comment by justincormack** [comment]
Hi, we don't have a doc link yet, I have asked the team to work on one.

**Comment by hickeyma** [comment]
That's grand @justincormack. Let us know when the doc is ready.

**Comment by justincormack** [comment]
Updated with the new docs page

**Pull request merged**
