### PR TITLE
ref(docs): import docs into v3.helm.sh

### PR DESCRIPTION
**Pull request by bacongobbler**
DO NOT MERGE until we get consensus from the core maintainers on this.

This is a significant development change to the documentation. Essentially, this moves the content of the `docs/` dir in helm/helm over to helm-www. This development approach is similar to kubernetes/kubernetes and kubernetes/website, where documentation now is PR'd against the website.

This provides several significant enhancements over the existing system:

1. No more URL redirect munging in gulpfile.js, which has caused us several issues in the past... https://github.com/helm/helm-www/issues/229 https://github.com/helm/helm-www/issues/190 https://github.com/helm/helm-www/issues/185 https://github.com/helm/helm-www/issues/181 https://github.com/helm/helm-www/issues/161 and https://github.com/helm/helm-www/issues/157, to name a few.
2. No need to clone helm/helm to build the site, which is a big blocker for adoption.
3. No need to open multiple PRs when introducing new documentation material (one for the docs, and one to add to the menus).
3. An opportunity to provide alternative locales, such as chinese or spanish.

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
Thanks for the review @flynnduism!

>     * :stop_sign: index templates are mixed up - the site landing page is a doc template whilst subsections use the homepage template. Not sure if you intended for this or not?

completely unintentional. Will take a closer look at this one.

>     * :stop_sign: template changes to the `sidebar.html` mean subpages are not shown

Yeah, this is something I'm having a bit of trouble working through. For the time being, what I did is that when you click on a sidebar link, the index.html for that topic loads, and the sub-topics are displayed as "quick links" - see image 2 above from your review.

I'd like to make the dropdown links work again but I'm having trouble getting that to work. I'll continue to try to figure out how that worked for the Helm 2 docs but if you have any pointers I'd love to hear them.

**Comment by flynnduism** [comment]
@bacongobbler I'm definitely game to help work on ironing out those final items.

Before doing more work can we seek consensus from the core maintainers?

**Comment by bacongobbler** [comment]
Absolutely. I'll kickstart the conversation today and seek consensus to move the docs over to helm-www this week.

**Comment by bridgetkromhout** [comment]
> significant workflow change for development on Helm - to create external PRs here

A quick glance through https://github.com/helm/helm/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Adocs makes it seem like the more frequent contributors are already involved with the project, so we may not have too many infrequent contributors to docs who would have trouble with a changed workflow.

**Comment by bacongobbler** [comment]
okay, the landing page is now a landing page, and the docs page now acts like the docs page.

Now running into https://github.com/netlify/netlify-cms/issues/513 which wasn't previously an issue as each subtopic was all merged into one index.html.

**Pull request merged**
