### PR TITLE
Updated Chinese translation, a typo/更新中文翻译，一个错别字

### PR DESCRIPTION
**Pull request by RockyFu267**

### CODE REVIEW

**Comment by RockyFu267** [comment]
@Zhanxueyou

**Comment by bridgetkromhout** [comment]
Hi, @RockyFu267! Thank you. Can you please sign the DCO? Here are the instructions: https://github.com/helm/helm-www/pull/1063/checks?check_run_id=2333253579

**Comment by RockyFu267** [comment]
It should be ok now :smiley:    @bridgetkromhout

**Review by bridgetkromhout — APPROVED** [review]
Thank you!

**Pull request merged**
