### PR TITLE
Add Chinese Translation.

### PR DESCRIPTION
**Pull request by bangwu**

### CODE REVIEW

**Comment by bangwu** [comment]
Please help to review it.

**Comment by bangwu** [comment]
hi @bridgetkromhout , Is it ready for merge?

**Comment by bridgetkromhout** [comment]
Hi, @bangwu - thank you for working on translation! Can you do two things:

1) remove any untranslated files
2) resolve any remaining merge conflicts

Then we can review this PR - thanks!

**Comment by bridgetkromhout** [comment]
Hi, @bangwu - since we cannot merge this due to merge conflicts, I'll close it without merging, but please do submit your changes in a new pull request if you like (after you pull in the changes from upstream)! Thanks.

**Pull request closed without merging**
