### PR TITLE
Update chart_repository.md

### PR DESCRIPTION
**Pull request by dnozay**
fix image links

### CODE REVIEW

**Comment by flynnduism** [comment]
Thanks @dnozay 

Before I can merge this, your commit [needs to be signed. Can you update?](https://github.com/helm/helm-www/pull/439/checks?check_run_id=348155020)

**Comment by flynnduism** [comment]
There is [another PR here](https://github.com/helm/helm-www/pull/430) mirroring these changes. I will merge whichever one incorporates the edits first!

**Comment by flynnduism** [comment]
Closing this, issue has been fixed via #430.

**Comment by dnozay** [comment]
👍 got busy with work thanks for fixing.

**Pull request closed without merging**
