### PR TITLE
[ZH] translate docs/intro/using_helm.md into Chinese

### PR DESCRIPTION
**Pull request by cvvz**
https://github.com/helm/helm-www/issues/958

### CODE REVIEW

**Comment by zhiguo-lu** [comment]
This file conflicts with PR  #957

**Comment by cvvz** [comment]
@zhiguo-lu PTAL. And you can use **insert a suggestion** button directly when leave a comment, that will be more convenient :)

**Comment by zhiguo-lu** [comment]
> @zhiguo-lu PTAL. And you can use **insert a suggestion** button directly when leave a comment, that will be more convenient :)

thanks, I'll put a try laterly.
/lgtm

**Comment by bridgetkromhout** [comment]
Hi, @cvvz! Thank you for your careful translation. Could you please resolve the merge conflicts so we can merge this?

I know the conflicts were my fault, because I did merge the PR https://github.com/helm/helm-www/pull/957 first, but we still would appreciate if the Chinese Helm community could also receive the benefits of your work. Thank you!

**Review by bridgetkromhout — APPROVED** [review]
Hi, @cvvz! Sorry for the delay - I have resolved the merge conflict and accepted your edits. Thank you for the translation!

**Pull request merged**
