### PR TITLE
[en] Clarify use of --set-file

### PR DESCRIPTION
**Pull request by davidxia**
and fix non-idiomatic English.

### CODE REVIEW

**Comment by davidxia** [comment]
Not sure who to tag for review. hail mary to @bacongobbler and @hickeyma

**Review by bridgetkromhout — COMMENTED** [review]
As these specific docs are generated, they need to be edited via this process: https://github.com/helm/helm-www#updating-the-helm-cli-reference-docs

**Comment by bridgetkromhout** [comment]
Hi, @davidxia - thanks for your PR! Those messages come from files we generate from the helm binary itself, so the places to edit those lines are here:
https://github.com/helm/helm/blame/main/cmd/helm/install.go#L52-L54
https://github.com/helm/helm/blame/main/cmd/helm/upgrade.go#L52-L54

So unfortunately we cannot merge this specific PR into the helm-www repo, but we would appreciate your changes in the helm code repo! Thanks.

**Comment by davidxia** [comment]
@bridgetkromhout thank you. New PR [here](https://github.com/helm/helm/pull/10424)

**Pull request closed without merging**
