### PR TITLE
docs(feature): add '--wait' option to 'uninstall' command

### PR DESCRIPTION
**Pull request by mikeshng**
document the '--wait' option to 'uninstall' command.

This PR is meant to go with https://github.com/helm/helm/pull/9702

Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @mikeshng - as these docs related to a PR that's not currently merged, I'm flagging it to be reviewed after https://github.com/helm/helm/pull/9702 is complete. Thanks.

**Comment by mikeshng** [comment]
Hi @bridgetkromhout just a FYI, the PR has been merged (to main branch waiting for a release) on the helm side. Thanks.

**Comment by bacongobbler** [comment]
Helm CLI docs need to be updated following the documentation [in the README](https://github.com/helm/helm-www#updating-the-helm-cli-reference-docs), as they all need to be updated at once. Once complete we can go ahead and merge this. Thanks!

**Review by bacongobbler — CHANGES_REQUESTED** [review]
does not follow procedure described in the README; on-hold until Helm 3.7.0 is released.

**Comment by bridgetkromhout** [comment]
Hi, @mikeshng - you can see from https://github.com/helm/helm-www/pull/1200 that this change came in via the update process described in https://github.com/helm/helm-www#updating-the-helm-cli-reference-docs - thanks! I'm closing this PR now as it is now not needed.

**Pull request closed without merging**
