### PR TITLE
[ko] Translate helm command : helm history in Korean

### PR DESCRIPTION
**Pull request by bluefriday**
Signed-off-by: bluefriday <bluefriday86@gmail.com>

[ko] Translate helm command : helm history in Korean

### CODE REVIEW

**Comment by bluefriday** [comment]
https://github.com/helm/helm-www/issues/971

**Comment by bluefriday** [comment]
@jmnote @jangdm @sunminjeon 리뷰 부탁드립니다.

**Comment by sunminjeon** [comment]
lgtm

**Review by bridgetkromhout — APPROVED** [review]
Thanks!

**Pull request merged**
