### PR TITLE
Updating the hub to the new location

### PR DESCRIPTION
**Pull request by mattfarina**

### CODE REVIEW

**Comment by mattfarina** [comment]
@bacongobbler @flynnduism what does it take for this to be deployed? Is there a visible pipeline somewhere?

**Comment by flynnduism** [comment]
Currently we've got a slackbot that deploys on demand - but that should be more accessible and auto-deploy on merge to master like this. 

Deployment is via [Brigade](https://github.com/azure/brigade), we can update the script to automate.

**Comment by dankohn** [comment]
CNCF has an account with Netlify, which does automated deployments and also automated previews of PRs. We're happy to set you up with a sub-account if you want to switch.

**Comment by flynnduism** [comment]
@dankohn thats good to know - I really like Netlify for static site projects. 

We're not looking to change our kubernetes-centric hosting/tooling, but the [readme needs updating](https://github.com/helm/helm-www/pull/110/) and the resources should be automated and accessible to all core personnel, we've some adjustments to make

**Pull request merged**
