### PR TITLE
Boat bob rides waves more realistically

### PR DESCRIPTION
**Pull request by Invincibear**
Boats in water don't just rise/sink vertically, their bow and stern dip up/down as they crest the waves of the water. This PR adds a slight rotation to simulate this.

### CODE REVIEW

**Comment by Invincibear** [comment]
Here is a preview of the changes: https://imgur.com/a/sFDV825

**Comment by vtgn** [comment]
> Here is a preview of the changes: https://imgur.com/a/sFDV825

Nice resut!

**Review by yxxhero — APPROVED** [review]

**Comment by yxxhero** [comment]
@karenhchu WDYT?

**Comment by karenhchu** [comment]
Amazing! Love this addition to the boat mechanics – thank you @Invincibear :shipit:

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
