### PR TITLE
rework the css boat animation

### PR DESCRIPTION
**Pull request by flynnduism**
Opening this to address #85. This reduces the animation from having 10 keyframes (w/ horizontal and vertical movements) to 2 keyframes of horizontal movement.

This is mostly done by using an animated gif for the boat, reducing the amount of css animation render work asked of the browser, which can be pretty cpu-gobbley.

### CODE REVIEW

**Comment by bacongobbler** [comment]
I noticed that the boat accelerates and decelerates due to the key-frame animation changes. Is there a way to make the acceleration at zero (constant horizontal movement)?

**Comment by flynnduism** [comment]
@bacongobbler yep that's the goal here. Simplifying the code = simpler movement.

Preview here: https://5c8ab2a3594fd40008ce5990--helm-merge.netlify.com 
@brendanstennett could you take a look at that url and see if the issue persists?

**Comment by flynnduism** [comment]
tweaked CSS to fix #188 too

Screen Shot 2019-03-14 at 12 45 21 PM

**Comment by bridgetkromhout** [comment]
Both the boat-animation change and the mobile layout content overlap fix == LGTM.

**Pull request merged**
