### PR TITLE
[helm.sh] blog post - emeritus maintainer rimas mocevicius

### PR DESCRIPTION
**Pull request by flynnduism**
Adds a new blog post: 

> Rimus Mocevicius (rimusz) has become the fourth Helm Emeritus Maintainer.

### CODE REVIEW

**Comment by rimusz** [comment]
Can you please correct my first name to Rimas :)

**Comment by rimusz** [comment]
also original founds of Helm -> original founders of Helm

**Comment by flynnduism** [comment]
Apologies Rimas! Corrected now, thanks for spotting this.

**Comment by rimusz** [comment]
shall we add there my last blog post https://rimusz.net/tillerless-helm url ? or repost on helm.sh?
we need that tiller story to be read by everybody :) as I get so many questions about tiller's security, this is why I wrote it.

**Comment by technosophos** [comment]
We could add one more line at the end that says: 

> Check out Rimas' latest blog post on [Tillerless Helm](https://rimusz.net/tillerless-helm).

**Pull request merged**
