### PR TITLE
Updating release_checklist.md

### PR DESCRIPTION
**Pull request by t2sa**
Updates release_checklist.md to match [PR#7277](https://github.com/helm/helm/pull/7277)

Signed-off-by: Thilak Somasundaram <t2same@gmail.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
DO NOT MERGE until upstream PR has been reviewed and merged

**Comment by flynnduism** [comment]
Following a change to the docs structure (#374), the file you're editing has been moved. 

This PR **will need a rebase** to ensure the edited file is in the new location. @t2sa let me know if I can help you with it!

```
moved from:
content/docs/community/release_checklist.md

to:
content/en/docs/community/release_checklist.md
```

**Comment by t2sa** [comment]
Thank you for the note @flynnduism

**Comment by mattfarina** [comment]
The shasum.txt file had issues with it. For example, being overwritten with every new release. That spawned https://github.com/helm/helm/issues/7567.  When that was fixed there were .sha256sum files. #525 is a PR to document that.

Closing this as it's overcome by events. I'm thankful of the work to push us to have shasum compatible checksums.

**Pull request closed without merging**
