### PR TITLE
Simplified Chinese document added

### PR DESCRIPTION
**Pull request by vinnyzhaowenyu**
Signed-off-by: vinnyzhaowenyu <admin@zhaowenyu.com>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @vinnyzhaowenyu!  thank you for working on translation! We merged another PR that translated these same files, so can you please resolve merge conflicts? Then we can review this PR - thanks!

**Comment by vinnyzhaowenyu** [comment]
> Hi, @vinnyzhaowenyu! thank you for working on translation! We merged another PR that translated these same files, so can you please resolve merge conflicts? Then we can review this PR - thanks!

ok, i will

**Comment by bridgetkromhout** [comment]
Hi, @vinnyzhaowenyu! Please sign the DCO and resolve the merge conflicts. See https://github.com/helm/helm-www/pull/761/checks?check_run_id=1046452724 - thanks.

**Comment by bridgetkromhout** [comment]
Hi, @vinnyzhaowenyu - since we cannot merge this due to merge conflicts, I'll close it without merging, but please do submit your changes in a new pull request if you like (after you pull in the changes from upstream)! Thanks.

**Pull request closed without merging**
