### PR TITLE
Update version_skew.md for 3.12

### PR DESCRIPTION
**Pull request by ReSearchITEng**

### CODE REVIEW

**Comment by ReSearchITEng** [comment]
Hi @angellk,
could you review & approve?

**Review by yxxhero — APPROVED** [review]

**Comment by ReSearchITEng** [comment]
thanks @yxxhero for approval.
What is the next step to have it merged?

**Comment by ReSearchITEng** [comment]
Hi @angellk, @hickeyma, @yxxhero , @bacongobbler, @bridgetkromhout , @flynnduism , @hickeyma  @jdolitsky , @karenhchu , @mattfarina , @technosophos ,
now that it's approved, can you please merge it?

**Comment by ReSearchITEng** [comment]
Hi,
what is the procedure to have this merged?

**Pull request merged**
