### PR TITLE
[ko] translate helm plugin command into Korean

### PR DESCRIPTION
**Pull request by bluefriday**
[ko] translate helm plugin command into Korean

### CODE REVIEW

**Comment by bluefriday** [comment]
@jmnote @sunminjeon @catchups @jangdm  리뷰 부탁드립니다.

**Comment by bluefriday** [comment]
https://github.com/helm/helm-www/issues/979

**Comment by sunminjeon** [comment]
LGTM

**Review by bridgetkromhout — APPROVED** [review]
Thank you!

**Pull request merged**
