### PR TITLE
Update helm-home.scss

### PR DESCRIPTION
**Pull request by rpsadarangani**
Fix Issue #418

### CODE REVIEW

**Comment by flynnduism** [comment]
Thanks @rpsadarangani good catch!

Before this can be merged, the DCO check needs to pass. Can you [sign your commit](https://github.com/helm/helm-www/pull/417/checks?check_run_id=327751954)?

**Comment by rpsadarangani** [comment]
I am facing issue in the commit, could you let me know the process

**Comment by flynnduism** [comment]
> I am facing issue in the signing commit, could you let me know the process

Sorry for the hassle @rpsadarangani - the steps to do so are [here](https://github.com/helm/helm-www/pull/417/checks?check_run_id=331761677):

> You only have one commit incorrectly signed off! To fix, head to your local branch and run:
> `git commit --amend --signoff`
> Now your commits will have your sign off. Next run
> `git push --force-with-lease origin fix-helm-home-feature-p`
> Commit sha: 9241191, Author: Rahul Sadarangani, Committer: Rahul Sadarangani; The sign-off is missing.

**Comment by rpsadarangani** [comment]
New Pull Request #428 is created with signed commit.

**Pull request closed without merging**
