### PR TITLE
Getting started essential fixes

### PR DESCRIPTION
**Pull request by fitz123**
These fixes make the sequence working  
```
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

### CODE REVIEW

**Comment by flynnduism** [comment]
Thank you for the PR @fitz123. I switched the base of this to `master` rather than `dev-v3-docs` as that branch has already been merged in and is now out of date.

---

One requirement is missing - your commits [needs to be signed off](https://github.com/helm/helm-www/pull/447/checks?check_run_id=364233034) as per the [DCO](https://probot.github.io/apps/dco/).

Can you update this PR? Instructions to do so are [here](https://github.com/helm/helm-www/pull/447/checks?check_run_id=364233034).

**Comment by bacongobbler** [comment]
ping

**Comment by fitz123** [comment]
All commits are signed-off both text (DCO) and PGP ways

**Comment by bacongobbler** [comment]
can you rebase your commits against master? We cannot merge it in its current state. Thanks.

**Pull request merged**
