### PR TITLE
kubectl config show -> view syntax change

### PR DESCRIPTION
**Pull request by marekaf**
show is not a subcommand, view it
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration

### CODE REVIEW

**Comment by mattfarina** [comment]
@marekaf thanks for the PR. Helm uses a [Developers Certificate of Origin](http://developercertificate.org/) to signify you have permission to contribute the change. Commits need to be made with `--signoff`. The checks tab at the top has directions on fixing the commit.

**Comment by bacongobbler** [comment]
pinging @marekaf

**Comment by marekaf** [comment]
> pinging @marekaf

honestly it is too much hassle to change few characters in docs
if anybody can "take over" this commit and PR, be my guest :))

**Comment by mattfarina** [comment]
Created a new PR to fix this at #565

**Pull request closed without merging**
