### PR TITLE
improve language switching

### LINKED ISSUE #687: improve language-switching behavior
When I click on the FAQ link in the left sidebar, which sends me to https://helm.sh/docs/faq/, I'm redirected to https://helm.sh/ko/docs/faq/ instead (in Korean, not English).  If I use the language chooser at the top of the page to switch back to English, I'm still redirected to the Korean translation.

### PR DESCRIPTION
**Pull request by flynnduism**
* show the language switcher on all pages
* link directly to the translated page (rather than homepage)
* conditionally hide links when translations do not exist
* include a prompt to encourage further translation

Closes #687.

### CODE REVIEW

**Comment by flynnduism** [comment]
Preview the site: https://deploy-preview-696--helm-merge.netlify.app/

Screenshots:

Screen Shot 2020-06-15 at 2 07 08 PM

_(when there **is** a Korean version of the page you are viewing available)_

Screen Shot 2020-06-15 at 2 07 23 PM

_(when there **is not** a Korean version of the page you are viewing available)_

**Comment by bridgetkromhout** [comment]
This is awesome! I noticed a few things that might be fixable:

https://deploy-preview-696--helm-merge.netlify.app/ko/ has a button with a translation of "Get Started" but the button takes you to the english quickstart even though https://deploy-preview-696--helm-merge.netlify.app/ko/docs/intro/quickstart/ exists in Korean

Do we have the text needed to translate these buttons?

image

I noticed that in the screenshot I just added, we don't have "Blog" at all, but I'm guessing that's a design decision? Otherwise, it's missing in the Korean index file.

Also the top banner is still the old one, in Korean. (Maybe that's intended, but FYI.)

**Comment by flynnduism** [comment]
Thanks @bridgetkromhout. 

1. ✅ **Get Started button**: this is a great point, the i18n configuration swaps out copy on the page but not urls. Links that are part of the nav/theme/etc need to be configurable - I have changed this here with the recent commits.

2. ✅ **Blog**: I've added a `/blog` link in the Korean menu. It points to the `en` site.

3. 🇰🇷  **Top banner**: These are seperated per language - recent edits were just to the `en` one. The korean banner is defined in the [ko.toml](https://github.com/helm/helm-www/blob/master/i18n/ko.toml#L12) if anyone wants to follow with a translation PR

**Comment by bridgetkromhout** [comment]
Looks great! Thanks for adding the ability to configure more.

**Pull request merged**
