### PR TITLE
Add Ukrainian translation for Helm documentation

### PR DESCRIPTION
**Pull request by Andygol**
This pull request contains a Ukrainian translation 🇺🇦  of the Helm documentation. Please review and merge.

image

### CODE REVIEW

**Comment by firemanxbr** [comment]
Hi @angellk, can you help us review or guide us through this PR? It's a nice improvement for the Ukrainian language.

**Comment by Andygol** [comment]
👋 Hi there.

I would be grateful for any activity on this PR. Naturally, it would be great if this PR would be merged with the `main` ☺️

**Comment by Andygol** [comment]
Hey @mattfarina, could you have a look at this pull request when you get a chance? 🙏

**Comment by firemanxbr** [comment]
Thank you so much for your work, @Andygol . Based on my understanding, this PR is good to merge. Let's wait for the final review and merge.

**Review by firemanxbr — APPROVED** [review]
LGTM

**Comment by karenhchu** [comment]
FYI I'm in the process of reviewing but it's taking a some time. Will try to aim to be done by EOW.

**Review by karenhchu — APPROVED** [review]
just a few small edits, otherwise LGTM!

**Comment by Andygol** [comment]
@karenhchu I've committed your suggestion. Feel free to go further and merge if other things look good.

**Comment by karenhchu** [comment]
Thank you for your contribution here @Andygol. Very much appreciated 🙏

**Pull request merged**
