### PR TITLE
fix(helm): update helm command docs to v3.0.3

### PR DESCRIPTION
**Pull request by bacongobbler**
commands like `helm home ` and `helm init` are no longer present in Helm 3.

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by flynnduism** [comment]
Thanks @bacongobbler. LGTM, ready to merge.

---

Non-blocking questions:

* I see this also restores the `helm get notes` command docs, which [had been missing](https://github.com/helm/helm-www/pull/401#issuecomment-575769751). Do you know if `helm inspect readme` is depreciated like `init` and `home`?
* The docs you brought over have the _See Also:_ urls edited, which [saves a step](https://github.com/helm/helm-www/pull/401/commits/f5156411cec15d76f55f4f272334485ac08962b5). Is this now changed at the source?

**Comment by bacongobbler** [comment]
`helm show` is an alias for `helm inspect` now, so if you run `helm inspect readme`, it will invoke `helm show readme`. Check out the last line in the output below:

```
><> helm help inspect

This command consists of multiple subcommands to display information about a chart

Usage:
  helm show [command]
```



>     * The docs you brought over have the _See Also:_ urls edited, which [saves a step](https://github.com/helm/helm-www/pull/401/commits/f5156411cec15d76f55f4f272334485ac08962b5). Is this now changed at the source?

Nah. I had to manually edit these links as well as the YAML front matter. We should probably figure out a better solution going forward, but it'll do for now :)

**Comment by zackbrown** [comment]
Hey @bacongobbler related to our convo over at https://github.com/helm/helm/issues/6996 I noticed that the "copy over generated docs" workflow doesn't seem to well address deletions

So I went together and spun up a script which makes the doc-copying a one-line `yarn update-docs`, and uses `rsync` along the way to delete files that should be deleted.  More info in that PR: https://github.com/helm/helm-www/pull/486

**Comment by bacongobbler** [comment]
Approved offline by @flynnduism. Merging!

**Pull request merged**
