### PR TITLE
Change banner to mention beta.1

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Currently, the banner atop the website mentions alpha 1, but we're on alpha 2 now.

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

### CODE REVIEW

**Comment by bacongobbler** [comment]
In preparation for the beta.1 release this week, could we change it to beta.1 and hold off until the release is out? That way we won't have to change the banner again in 2 days time.

**Comment by flynnduism** [comment]
No probs… the addition of the versioning dropdown (#241) removed the sticky message banner which is causing this conflict.

My thinking was that the dropdown handles the same job as this banner - but now it only appears on the `helm.sh/docs/` sections... looking at this again I think the homepage and blog sections should keep the banner so there's a clear route between v2 and v3.

**Comment by Nodraak** [comment]
> In preparation for the beta.1 release this week

Is there an official release date? Or are you waiting for a specific issue to be closed?

**Comment by Nodraak** [comment]
> @Nodraak see [beta.1](https://github.com/helm/helm/releases/tag/v3.0.0-beta.1)

Many thanks! I had some issues trying to deploy prometheus-operator with Helm v3 alpha 2, therefore I'm looking forward trying again with this new release.

**Comment by bridgetkromhout** [comment]
Closing in favor of https://github.com/helm/helm-www/pull/269.

**Pull request closed without merging**
