### PR TITLE
Update Chinese docs

### PR DESCRIPTION
**Pull request by 880831ian**
Signed-off-by: PinYi <880831ian@gmail.com>

### CODE REVIEW

**Comment by 880831ian** [comment]
I want to help translate Traditional Chinese

**Comment by yxxhero** [comment]
@880831ian Thank you for your work, please use simplified Chinese.

**Comment by yxxhero** [comment]
@880831ian  Or you can open a new traditional Chinese menu. What do you think?

**Comment by 880831ian** [comment]
I have this plan

**Comment by yxxhero** [comment]
@880831ian Just do it.

**Comment by yxxhero** [comment]
@880831ian I will close this issue. if your Traditional Chinese is done. Please create a new PR. Thanks very much.

**Pull request closed without merging**
