### PR TITLE
document execute flag rename

### PR DESCRIPTION
**Pull request by heydonovan**
This is in reference to: https://github.com/helm/helm/issues/6290#issuecomment-564253567

### CODE REVIEW

**Comment by bacongobbler** [comment]
ping

**Comment by hickeyma** [comment]
@heydonovan Do you mind signing the dco and rebasing?

**Comment by flynnduism** [comment]
In addition to the required DCO sign-off, this PR will also **need a rebase** to ensure the edited file is in the new location (due to directory changes in #374). 

@heydonovan let me know if I can help you with it!

```
moved from:
content/docs/topics/v2_v3_migration.md

to:
content/en/docs/topics/v2_v3_migration.md
```

**Comment by heydonovan** [comment]
@flynnduism I think I did it right, let me know if you just want me to open a new PR.

**Pull request merged**
