### PR TITLE
[ko] Translate helm search of helm command in Korean

### PR DESCRIPTION
**Pull request by bluefriday**
Signed-off-by: bluefriday86 <bluefriday86@gmail.com>

[ko] Translate helm search of helm command in Korean

### CODE REVIEW

**Comment by bluefriday** [comment]
https://github.com/helm/helm-www/issues/983

**Comment by bluefriday** [comment]
@jmnote @jangdm @catchups @singlemocha @jmyung  리뷰 부탁드립니다.

**Comment by sunminjeon** [comment]
LGTM

**Review by bridgetkromhout — APPROVED** [review]
Thank you!

**Pull request merged**
