### PR TITLE
Add helm v3 docs

### PR DESCRIPTION
**Pull request by lemonit-eric-mao**
- **Base repository**: `helm/helm-www`
   - **Base**: `main`
   - **Head repository**: `https://github.com/lemonit-eric-mao/helm-www/tree/add-helm-v3-docs`
   - **Compare**: `add-helm-v3-docs`

### CODE REVIEW

**Review by flynnduism — APPROVED** [review]
Thanks for contributing to Helm @lemonit-eric-mao !

I looked over these (with help from translations) and they are 👍🏻 
Appreciate the help, thanks

**Review by flynnduism — CHANGES_REQUESTED** [review]
The edits are good, but your commit [needs to be signed](https://github.com/helm/helm-www/pull/1489/checks?check_run_id=15357646497) for this to be merged. More info [here](https://helm.sh/blog/helm-dco/#what-is-a-dco) on DCO and signing

**Review by yxxhero — APPROVED** [review]

**Comment by yxxhero** [comment]
@lemonit-eric-mao please squash your commits into one commit.

**Comment by lemonit-eric-mao** [comment]
I'm sorry for any confusion. I've made the necessary adjustments as you requested.

**Comment by yxxhero** [comment]
@lemonit-eric-mao  you should finish 
image
then I can merge this PR.

**Review by yxxhero — APPROVED** [review]

**Comment by lemonit-eric-mao** [comment]
Hi~! @flynnduism
Could you please help review and approve this pull request?
or please advise is there any further step I need complete?

**Review by flynnduism — APPROVED** [review]

**Comment by flynnduism** [comment]
Sorry for the delay @lemonit-eric-mao - this is approved, merging now. 

Thank you for this contribution! 🙌

**Pull request merged**
