### PR TITLE
Feat/add docsearch

### LINKED ISSUE #56: Add search to the docs
See issue [#2698](https://github.com/kubernetes/helm/issues/2698).

### PR DESCRIPTION
**Pull request by s-pace**
👋 Hello team,

Following helm/helm#4679, this PR add a search experience to the docs.

I'm part of [the project called DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like Bootstrap, Reactjs or Gulp.

I have created a quick demo of what DocSearch enables on your documentation thanks to this PR. You [can try it out here](https://docsearch-helm.surge.sh/docs/).
[Live Demo](https://docsearch-helm.surge.sh/docs/)

Happy to update the PR if needed.

Resolves  #56

### CODE REVIEW

**Comment by flynnduism** [comment]
Sylvian this is perfect!  🎉🎉🎉

Thank you for integrating this. Happy to 👍 this PR

**Comment by s-pace** [comment]
@flynnduism thank you for the feedback 🙏. I have just cleaned up the noise introduced by the PR.

Feel free to ping me if you need anything before merging it.

**Comment by bacongobbler** [comment]
Hi @s-pace! Thank you for working on this and showing us docsearch. Very neat piece of tech :+1: 

I had a question about the billing model. By merging this PR, are we subject to the [pricing models](https://www.algolia.com/pricing) displayed on the site? Is this service free for open source projects like Helm, or are we subject to the same billing model as others? How does that work? Thanks!

**Comment by s-pace** [comment]
Hi @bacongobbler,

Thank you for your feedback 🎉. DocSearch is entirely free for open source project :). Helm does qualify in its entirely.

If you want to have access to the analytics we provide for your DocSeach index (`helm`), please [apply from here](https://community.algolia.com/docsearch/apply.html).

**Comment by bridgetkromhout** [comment]
Checked out https://docsearch-helm.surge.sh/docs/ and it looks good. Also checked out the local preview: https://deploy-preview-194--helm-merge.netlify.com/docs/ - LGTM.

**Comment by s-pace** [comment]
@bridgetkromhout Thank you for the feedback 🙏 

@bacongobbler Let us know if you need anything to make this happen 🔍

**Pull request merged**
