### PR TITLE
Add Chinese doc first time.

### PR DESCRIPTION
**Pull request by Zhanxueyou**
Signed-off-by: zhanxueyou <zhanxueyou@msn.com>

### CODE REVIEW

**Comment by flynnduism** [comment]
@Zhanxueyou this is wonderful, thank you for doing this work! 🙌 

There is an issue with the [build](https://app.netlify.com/sites/helm-merge/deploys/5f3f3c58b3a0ab000846988f), because there are some links that don't work on the Chinese language site.

```
8:16:30 PM: ========================================================================
8:16:30 PM: zh/404.html
8:16:30 PM:   target does not exist --- zh/404.html --> /zh/blog
8:16:30 PM:   target does not exist --- zh/404.html --> /zh/blog
8:16:30 PM: zh/index.html
8:16:30 PM:   target does not exist --- zh/index.html --> /zh/blog
8:16:30 PM:   target does not exist --- zh/index.html --> /zh/blog
8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/topics/architecture/
8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/quickstart/
8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/install/
8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/install/
8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/using_helm/
8:16:30 PM: zh/docs/index.html
8:16:30 PM:   target does not exist --- zh/docs/index.html --> /zh/blog
8:16:30 PM:   target does not exist --- zh/docs/index.html --> /zh/blog
8:16:30 PM:   target does not exist --- zh/docs/index.html --> intro
8:16:30 PM:   target does not exist --- zh/docs/index.html --> topics
8:16:30 PM:   target does not exist --- zh/docs/index.html --> community
8:16:30 PM:   target does not exist --- zh/docs/index.html --> howto
8:16:31 PM: ========================================================================
```

To make the link checker ✅ I think these links can either be (i) pointed to the `en` site content (absolute urls like we did with [some of the Korean links](https://github.com/helm/helm-www/blob/master/config.toml#L142)) or (ii) remove them for now, pending further translations.

**Comment by Zhanxueyou** [comment]
> 
> 
> @Zhanxueyou this is wonderful, thank you for doing this work! 🙌
> 
> There is an issue with the [build](https://app.netlify.com/sites/helm-merge/deploys/5f3f3c58b3a0ab000846988f), because there are some links that don't work on the Chinese language site.
> 
> ```
> 8:16:30 PM: ========================================================================
> 8:16:30 PM: zh/404.html
> 8:16:30 PM:   target does not exist --- zh/404.html --> /zh/blog
> 8:16:30 PM:   target does not exist --- zh/404.html --> /zh/blog
> 8:16:30 PM: zh/index.html
> 8:16:30 PM:   target does not exist --- zh/index.html --> /zh/blog
> 8:16:30 PM:   target does not exist --- zh/index.html --> /zh/blog
> 8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/topics/architecture/
> 8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/quickstart/
> 8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/install/
> 8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/install/
> 8:16:30 PM:   target does not exist --- zh/index.html --> ./docs/intro/using_helm/
> 8:16:30 PM: zh/docs/index.html
> 8:16:30 PM:   target does not exist --- zh/docs/index.html --> /zh/blog
> 8:16:30 PM:   target does not exist --- zh/docs/index.html --> /zh/blog
> 8:16:30 PM:   target does not exist --- zh/docs/index.html --> intro
> 8:16:30 PM:   target does not exist --- zh/docs/index.html --> topics
> 8:16:30 PM:   target does not exist --- zh/docs/index.html --> community
> 8:16:30 PM:   target does not exist --- zh/docs/index.html --> howto
> 8:16:31 PM: ========================================================================
> ```
> 
> To make the link checker ✅ I think these links can either be (i) pointed to the `en` site content (absolute urls like we did with [some of the Korean links](https://github.com/helm/helm-www/blob/master/config.toml#L142)) or (ii) remove them for now, pending further translations.

OK, great. I got it.

**Comment by flynnduism** [comment]
@Zhanxueyou sorry for the confusion with this. The link checker test is passing now, but reviewing the commits I am requesting changes to make this ready for merging -

 I see english languages files added in ([1595d6](https://github.com/helm/helm-www/pull/777/commits/1dee5ff770fc439755787cecffa9bfbb591595d6)). You copied the `en` content for the blog and the docs into the `zh` section of the site, to get around the [build errors](https://app.netlify.com/sites/helm-merge/deploys/5f3f3c58b3a0ab000846988f). This is not ideal as it creates confusion by duplicating content and mixes up languages.  

* **I recommend reverting the last commit** - removing the english language files. 
* Then this PR can merge (I can overwrite the link checker)
* I will follow up with a PR to resolve the links between the `zh` and `en` sites

**Comment by Zhanxueyou** [comment]
> 
> 
> Remove these files, then I can issue a follow-up PR to get the link check in the build to pass.
> 
>     * content/zh/blog
> 
>     * content/zh/docs  _(but keep the `_index.md` file that you [translated](https://github.com/helm/helm-www/pull/777/files#diff-e60be8a05f28059c79e25f04b848070c))_

OK, sorry for that. Please check it again.

**Comment by Zhanxueyou** [comment]
> 
> 
> Remove these files, then I can issue a follow-up PR to get the link check in the build to pass.
> 
>     * content/zh/blog
> 
>     * content/zh/docs  _(but keep the `_index.md` file that you [translated](https://github.com/helm/helm-www/pull/777/files#diff-e60be8a05f28059c79e25f04b848070c))_

OK, sorry for that. Please check it again.

**Pull request merged**
