### PR TITLE
Improve rendering of commands for shell completion

### PR DESCRIPTION
**Pull request by zigarn**
Before:
image

After:
image

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @zigarn - unfortunately a number of those files are generated, so the English docs need to be updated in this way: https://github.com/helm/helm-www#updating-the-helm-cli-reference-docs

After the English docs are re-generated, then we can merge updated translations.

**Comment by zigarn** [comment]
@bridgetkromhout OK, I understand.

But then, to make it look good in generated markdown, I have to make it look less good in CLI help:

```
Generate the autocompletion script for Helm for the bash shell.

To load completions in your current shell session:

    $ source <(helm completion bash)

To load completions for every new session, execute once:
- Linux:

      $ helm completion bash > /etc/bash_completion.d/helm

- MacOS:

      $ helm completion bash > /usr/local/etc/bash_completion.d/helm

Usage:
  helm completion bash
```

Or

```
Generate the autocompletion script for Helm for the bash shell.

To load completions in your current shell session: `source <(helm completion bash)`

To load completions for every new session, execute once:
- Linux: `helm completion bash > /etc/bash_completion.d/helm`
- MacOS: `helm completion bash > /usr/local/etc/bash_completion.d/helm`

Usage:
  helm completion bash
```

**Comment by bridgetkromhout** [comment]
> But then, to make it look good in generated markdown, I have to make it look less good in CLI help:

Indeed, there are tradeoffs. Go ahead and submit your preference to helm/helm; when we get it in there, then we can merge translations here. Thanks!

**Comment by zigarn** [comment]
Generated completion docs from helm/helm#9718 + adapted translations.

**Comment by bridgetkromhout** [comment]
> generated completion docs from helm/helm#9718 + adapted translations.

Great; thanks! We now need to wait to merge this until that gets related.

**Comment by bridgetkromhout** [comment]
This is in the 3.7 milestone, slated for release in September. The merge conflicts are because of the 3.6 release today.

**Comment by bacongobbler** [comment]
Should we close this for now? This change will be pulled in after Helm 3.7.0 has been released and we update the reference docs.

**Comment by bridgetkromhout** [comment]
Hi, @zigarn - I see what is confusing. Yes, the docs do need to be generated, but also, we do not merge changes to the generated docs until the release occurs. So this PR will not be merged until September, and at that point, it still would need the English entries removed. The English entries would only be updated with a PR after the release, like this: https://github.com/helm/helm-www/pull/1120

For those reasons, I will close this PR as suggested by @bacongobbler above. (While it might seem like a good idea to keep it open just for the translated docs, I'm concerned that sitting for months will lead to many merge conflicts.) After the 3.7.0 release, you or any other community member can submit updates to the translated docs. Thanks!

**Pull request closed without merging**
