### PR TITLE
[pt] Adding Portuguese Language 

### PR DESCRIPTION
**Pull request by moraesjeremias**
## This Pull Request adds Portuguese Language to Helm's Docs.

The localization contribution minimum requirements are satisfied within this PR.

## This PR follows:
- [x] [Helm's Localization Guide](https://helm.sh/docs/community/localization/) 
- [x] [ISO 639-1](https://www.loc.gov/standards/iso639-2/php/code_list.php)
- [x] [Contribution Guide Lines](https://github.com/helm/helm-www/blob/main/CONTRIBUTING.md)
- [x] [Helm's and CNCF's Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)
- [x] [DCO Agreement](https://developercertificate.org/)

### Personal Notes:
Tried as much to bring Portuguese IT industry terms as did @nikfot in [Add Greek Language
](https://github.com/helm/helm-www/pull/1095#issuecomment-835142054) for Greek.

Signed-off-by: Jeremias Moraes <moraesjeremias@gmail.com>

### CODE REVIEW

**Review by flynnduism — CHANGES_REQUESTED** [review]
@moraesjeremias thank you for this effort to create a Portuguese language version of the docs site, this is amazing to see!

To get this PR merged, there is a build issue that needs to be resolved (log of the [error is here](https://app.netlify.com/sites/helm-merge/deploys/6106c4fbb29d30000715d592)), to summarize, there is a strict html link checker that runs during the build process, and it fails when it sees that there are urls in the website homepage:

```
9:00:34 AM: ========================================================================
9:00:35 AM: pt/index.html
9:00:35 AM:   target does not exist --- pt/index.html --> ./docs/topics/architecture/
9:00:35 AM:   target does not exist --- pt/index.html --> ./docs/intro/quickstart/
9:00:35 AM:   target does not exist --- pt/index.html --> ./docs/intro/install/
9:00:35 AM:   target does not exist --- pt/index.html --> ./docs/intro/install/
9:00:35 AM:   target does not exist --- pt/index.html --> ./docs/intro/using_helm/
9:00:35 AM: ========================================================================
9:00:35 AM: ✘✘✘ failed in 922.727239ms
9:00:35 AM: 5 errors in 556 documents
```

These links are defined in the `pt.toml` file - they don't go anywhere in the Portuguese site, as those pages aren't translated yet. To make this pull request pass, you could remove the links for now, and they can be re-added later on if those pages are translated.

* [Link to Architecture](https://github.com/helm/helm-www/blob/6361f15636cbb661fe6f400681f34232770e37cf/i18n/pt.toml#L56)
* [Link to Quickstart](https://github.com/helm/helm-www/blob/6361f15636cbb661fe6f400681f34232770e37cf/i18n/pt.toml#L8) 
* [Link to Install](https://github.com/helm/helm-www/blob/6361f15636cbb661fe6f400681f34232770e37cf/i18n/pt.toml#L96) (twice)
* [Link to Using Helm](https://github.com/helm/helm-www/blob/6361f15636cbb661fe6f400681f34232770e37cf/i18n/pt.toml#L96)

It is preferred to remove links rather than point them to the `en` equivalent or another language version, as crossing links between languages gets confusing and is best avoided.

---

Thank you for contributing these edits to Helm!

**Comment by bridgetkromhout** [comment]
The easiest path to resolve what @flynnduism's is explaining is to use the English versions of those links. I've made that edit for the time being.

**Review by angellk — APPROVED** [review]
thanks for your contribution @moraesjeremias ! looks great

**Comment by moraesjeremias** [comment]
Thank you @flynnduism and @bridgetkromhout for help and assistance!
I hope I can manage my agenda to contribute to Helm localization at least once in a week, I'll try my best!
I'm very excited to help you guys! Thanks for the opportunity!

**Pull request merged**
