### PR TITLE
Adding deprecated APIs link to sidebar

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Addition for https://github.com/helm/helm-www/pull/925

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>
Co-authored-by: Martin Hickey <martin.hickey@ie.ibm.com>

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Comment by bridgetkromhout** [comment]
Okay, @hickeyma - see https://deploy-preview-930--v2-helm.netlify.app/docs/ for the preview - is this what you envisioned?

image

**Review by flynnduism — APPROVED** [review]

**Review by hickeyma — COMMENTED** [review]
Thanks for pushing this @bridgetkromhout. Hmm, looking at it now, I am not so sure that it is the best place to put it. Do folks think it should be within "Using Helm" or on its own like "Developer Guide"? It is kind of a special/advanced topic.

**Comment by bridgetkromhout** [comment]
>  I am not so sure that it is the best place to put it. Do folks think it should be within "Using Helm" or on its own like "Developer Guide"? It is kind of a special/advanced topic.

Anyone who uses Helm does need to pay attention to k8s API deprecation, because APIs going away will likely cause problems for an ever-increasing number of users. I think keeping it here seems okay until the next time we re-organize docs.

**Comment by hickeyma** [comment]
I think that is reasonable @bridgetkromhout.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @bridgetkromhout

**Pull request merged**
