### PR TITLE
Add plugins info for helm-s3 and helm-schema-gen

### LINKED ISSUE #450: Add info about helm-s3 plugin
https://helm.sh/docs/community/related/#helm-plugins

### LINKED ISSUE #451: Add info about helm-schema-gen plugin
https://helm.sh/docs/community/related/#helm-plugins

### PR DESCRIPTION
**Pull request by karuppiah7890**
This PR adds info about `helm-s3` plugin and `helm-schema-gen` plugin

Fixes #450 
and
Fixes #451

### CODE REVIEW

**Comment by thomastaylor312** [comment]
Good to go pending rebase

**Comment by flynnduism** [comment]
@karuppiah7890 can you rebase this PR? Once the conflicting file is resolved it can be merged.

**Comment by karuppiah7890** [comment]
Sure! 👍

**Comment by karuppiah7890** [comment]
@flynnduism it's done now 😄

**Pull request merged**
