### PR TITLE
feat(content): internationalization support

### PR DESCRIPTION
**Pull request by bacongobbler**
this is a slight alternative to the proposal laid out in #274:

- all references to documentation in chinese has been removed (as there is no translation available at this time)
 - refactored out the `i18n` directory. Instead, I refactored the homepage partial and moved the main homepage content under `content/en/_index.md` to allow for translations of the homepage
- all content (except `content/code` which is only relevant for https://helm.sh) has been restored and moved over to `content/en`

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
After pairing with @flynnduism on this PR, it looks like the /en and /fr (if there's french documentation available) isn't properly set up, even if the content exists. Looking further into the Hugo docs to see what changes are necessary to support that workflow.

**Comment by lucperkins** [comment]
@bacongobbler I’m not sure I understand the intent behind some of these changes. The i18n directory already enables translations of the home page and is the canonical way to handle localization in Hugo.

**Comment by bacongobbler** [comment]
The main reason had to do with presentation of the content. The content that was moved out of the layout was just text wrapped in a `<section>` tag. The content itself is all wrapped in `<div>`, `<p>` and various sizes of `<h>` tags which can all be easily converted to markdown. The content itself should not be part of the layout, but the content has *structure*. The homepage isn't a bunch of strings all sparsed in different parts of the page; it's all one chunk of consumable content.

That was my main gripe with the `i18n` approach in #274 - by referencing the content as functions, we were only storing the paragraphs as strings. There was no meaning behind the content. This makes sense for "catch phrases" and one-liners (or template partials that should be included as a header or a footer in all documents), but it doesn't make sense to break up a chunk of content into tiny bite-sized pieces.

Additionally, the `i18n` approaches the content with a different separation of concerns. The `i18n` approach determines that the page's layout should dictate how the content should be presented. With the content of the homepage under `content/en/_index.md`, the content dictates how it should be presented to the user, and it's up to the layout to design the page around the content, not the other way around.

Does that make sense?

**Comment by bacongobbler** [comment]
As for 
> You can see [here](https://deploy-preview-274--helm-v3-dev.netlify.com/zh/) that the changes in #274 have enabled a Chinese translation of the main page and docs. The only required work there is translating the snippets in `i18n/zh.toml`.

That's interesting to know. Thank you. I figured I must've set something up wrong compared to how it was done in #274. I'll take another stab at it tomorrow.

**Comment by bacongobbler** [comment]
That being said, I missed some of the changes made in #274 where it *did* make sense to put into the `i18n` directory like the banner content. I'll review that further as well. Thanks for pointing that out!

**Comment by lucperkins** [comment]
@bacongobbler I think the wires are still a bit crossed here. Using the approach I adopted in #274, all you have to do to translate the home page for a language is translate the snippets in `i18n/LANGUAGE.toml`. That will produce a homepage that looks exactly like the current home page, just translated. See the layout [here](https://github.com/lucperkins/helm-www/blob/lperkins/i18n-support/themes/helm/layouts/index.html).

Embedding raw HTML in the Markdown file means that any change to the homepage will need to involve copy/pasting across different `_index.md` files *with* corresponding changes to the text, which could get messy as the number of languages expands. With the approach in #274, the aesthetic can be changed in one place.

**Comment by bacongobbler** [comment]
You're totally right @lucperkins. I'll close this and re-open a new PR that just rebases your PR on top of the existing content. Thanks!

**Pull request closed without merging**
