### PR TITLE
Create og image and set meta tags

### PR DESCRIPTION
**Pull request by urre**
Created a nicer open graph image, instead of just the favicon, used when the website is shared on social networks.

### CODE REVIEW

**Comment by mattfarina** [comment]
@urre Thanks for creating this. Helm uses a [developers certificate of origin](https://developercertificate.org/) to signify that you can contribute. That's the check that failed. When you git commit it needs a `--signoff` flag. Under the checks tag there are directions on fixing your existing commit. Could you please do that.

**Comment by mattfarina** [comment]
@urre Thanks for the update but the signoff is off again. Can you fix it?

**Comment by urre** [comment]
@mattfarina sorry, did I do i correct now?

**Comment by bacongobbler** [comment]
unfortunately no. Your first commit (6abe0cd) is not signed off, so the check is failing. You will need to perform an interactive rebase to edit this commit. See https://confluence.atlassian.com/stashkb/how-do-you-make-changes-on-a-specific-commit-747831891.html for some helpful tips on how to do this.

**Comment by bacongobbler** [comment]
pinging @urre

**Comment by flynnduism** [comment]
[Tested](https://cards-dev.twitter.com/validator) the new image, looks nice @urre! 
Thanks for this. Once commits are signed, this is 👍 

Screen Shot 2020-04-13 at 11 55 06 AM

**Comment by urre** [comment]
@flynnduism sorry, i've tried some different things, but doesn't seem to manage to sign off this commit now afterwards. I can do another PR in another branch and you can close and remove this one.

**Comment by hickeyma** [comment]
@urre Did you try the following command: `git commit --amend -s` ?

**Comment by urre** [comment]
@hickeyma yes, i've tried
```
git commit --amend --signoff
git push --force-with-lease origin feat/og-image
```

but I can't get pass the DCO checks

**Comment by hickeyma** [comment]
@urre Try changing this command `git push --force-with-lease origin feat/og-image` to `git push -f origin feat/og-image`

**Comment by bacongobbler** [comment]
Looking at [the commit history here](https://github.com/helm/helm-www/pull/548/commits), your very first commit is still missing the signoff. You will need to go back and amend commit 6abe0cddb8900e88feec58cb088c9f9c5cccdeed. Have you tried the instructions I provided earlier? https://github.com/helm/helm-www/pull/548#issuecomment-602809187

**Comment by urre** [comment]
@bacongobbler tried it, but screwed up somehow. Didn't manage to rebase -i from that commit and sign it off

**Comment by hickeyma** [comment]
@urre It might be worth closing this PR then and opening a new one. Just remember to pass the `-s` flag with the commit.

**Pull request closed without merging**
