### PR TITLE
Reinstate the helm command docs

### PR DESCRIPTION
**Pull request by flynnduism**
## Needs help before review 

Issue #383 flagged some content that we're missing since we moved rom v2 to v3 docs. Changes in where the docs are stored and how they're built has impacted on their inclusion, but IMO we should display them here if at all possible.  

I've made a start on that here, but with content that is out of date. This PR contains contains content from v2. Before this PR is mergeable I need to run `make docs` (or whatever the new process is) to **extract the latest markdown content** from helm/helm.

### Checklist:

- [x] export latest helper content for all `helm _____` commands
- [x] import markdown
- [x] index with front matter as needed 
- [x] ensure new section renders nav links 
- [x] ensure templates can properly display browsable list commands

### CODE REVIEW

**Comment by StephenBrown2** [comment]
Minor note: https://github.com/spf13/cobra/blob/master/doc/md_docs.md

**Comment by bacongobbler** [comment]
Originally, we removed this section from the documentation as it was a massive blocker for users wishing to contribute documentation to Helm.

In order to re-build the CLI reference, you required the ability to build the helm CLI from source, which for many users is a major blocker for contributing to the docs... There very few users who are comfortable with Go, and even fewer comfortable with Go and Hugo.

How can we reconcile that here? The only way I can imagine we address that is by setting up a netlify script that pulls the latest version of Helm down and re-generates the CLI reference every build. Perhaps that's an option here?

**Comment by StephenBrown2** [comment]
> The only way I can imagine we address that is by setting up a netlify script that pulls the latest version of Helm down and re-generates the CLI reference every build. Perhaps that's an option here?

That would be a good option, I think, though there would need to be some minor massaging before it'd be good to go, namely: the header information (title and description) need to be grabbed from the first three lines of the generated docs, and the SEE ALSO links at the bottom need to be redirected to `../` and have the `.md` extension removed.

**Comment by bacongobbler** [comment]
`helm docs` has an option to be rendered as HTML (via `--output html`). That could be used to work around that.

**Comment by StephenBrown2** [comment]
html output would be good, though I didn't see that as an option when I ran `helm docs --help`:
```
Generate documentation files for Helm.

This command can generate documentation for Helm in the following formats:

- Markdown
- Man pages

It can also generate bash autocompletions.

Usage:
  helm docs [flags]

Flags:
      --dir string    directory to which documentation is written (default "./")
  -h, --help          help for docs
      --type string   the type of documentation to generate (markdown, man, bash) (default "markdown")
```
The links would still need to be adjusted.

**Comment by bacongobbler** [comment]
I stand corrected. Either way, we were able to work around it in Helm 2's documentation; I'm sure we can take a similar approach here as well.

**Comment by mattfarina** [comment]
@flynnduism where does this stand? I see one final task in the checkboxes.

**Comment by flynnduism** [comment]
@mattfarina this PR reinstates that section to the site, updates menus etc. However the uncertain part is extracting the latest `helm cmd` help content from main project repo itself. The content here in this PR is still based on v2.

In v2, `mkdocs` exported markdown for this and we rendered this within the docs website.  The script that published it is no longer in place. I need help figuring out how to export the most-up-to-date help text to publish it here.

**Comment by flynnduism** [comment]
Actually I can do this with the info @bacongobbler provided - running `helm docs --type markdown` generates the content I need to complete this PR.

**Comment by flynnduism** [comment]
Screen Shot 2020-01-13 at 1 19 44 PM


Ok the latest help text content has been imported and indexed. This is ready for review:
[https://5e1cdeae86b7440007fd1286--helm-merge.netlify.com/docs/helm/helm/](https://5e1cdeae86b7440007fd1286--helm-merge.netlify.com/docs/helm/helm/)

**Comment by flynnduism** [comment]
I noted that two of the CLI commands from v2 are not documented here. 

```
helm get notes
helm inspect readme
```

Assuming these are depreciated?

**Comment by bacongobbler** [comment]
they weren't ported over I think. I believe they're open issues for Helm 3 to bring back as I understand

**Comment by bacongobbler** [comment]
We can add them to the CLI reference once they've been reintroduced

**Comment by bacongobbler** [comment]
Hey @flynnduism! Is this PR ready for another review? Let me know and I can take another look. Thanks!

**Comment by flynnduism** [comment]
@bacongobbler I think this is good to go.

I was unsure about the missing content - we can follow up separately with the docs for `helm get notes` and`helm inspect readme` once those are reinstated in the main project.

**Comment by flynnduism** [comment]
@bacongobbler thanks, I've updated the [readme](https://github.com/helm/helm-www/pull/401/files#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by StephenBrown2** [comment]
The links from the `see also` pages don't line up with the paths on the site. e.g.
`helm home` on [the index](https://5e1cdeae86b7440007fd1286--helm-merge.netlify.com/docs/helm/helm/) goes to [/docs/helm/helm/helm_home.md](https://5e1cdeae86b7440007fd1286--helm-merge.netlify.com/docs/helm/helm/helm_home.md) rather than [/docs/helm/helm_home/](https://5e1cdeae86b7440007fd1286--helm-merge.netlify.com/docs/helm/helm_home/) where it exists.

**Comment by flynnduism** [comment]
Good catch @StephenBrown2. I added a fix to correct those `see also` links.
Preview [here](https://deploy-preview-401--helm-merge.netlify.com/docs/helm/helm/#see-also). If that looks 👍 I will merge this.

**Comment by StephenBrown2** [comment]
LGTM, should there also be a step in [the README](https://github.com/helm/helm-www/pull/401/files#diff-04c6e90faac2675aa89e2176d2eec7d8R46-R53) to fix them on update?

**Comment by flynnduism** [comment]
> LGTM, should there also be a step in [the README](https://github.com/helm/helm-www/pull/401/files#diff-04c6e90faac2675aa89e2176d2eec7d8R46-R53) to fix them on update?

Yep, this PR updates the Readme to do so [here](https://github.com/helm/helm-www/pull/401/commits/f0539e1b1888c350e8f31987183f2ff05976a514).

**Comment by StephenBrown2** [comment]
Yes, that's what I linked[1], but there isn't a step to fix the SEE ALSO links.

[1] the README: https://github.com/helm/helm-www/pull/401/files#diff-04c6e90faac2675aa89e2176d2eec7d8R46-R53

**Comment by flynnduism** [comment]
> Yes, that's what I linked[1], but there isn't a step to fix the SEE ALSO links.

D'oh, I'm sorry. That makes total sense @StephenBrown2. I will amend with a follow up PR.

**Pull request merged**
