### PR TITLE
feat(helm): optionally hide validation warnings

### PR DESCRIPTION
**Pull request by rcousineau-xandr**
accompanies https://github.com/helm/helm/pull/9604

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @rcousineau-xandr - thank you for the PR! This kind of CLI reference docs change needs to be made in the https://github.com/helm/helm repo itself. For more info, please see this section of this repo's README: https://github.com/helm/helm-www#updating-the-helm-cli-reference-docs

**Comment by rcousineau-xandr** [comment]
@bridgetkromhout  hrmm, sorry.

I was following this guide https://helm.sh/docs/community/developers/#writing-documentation

**Comment by bridgetkromhout** [comment]
I agree that guide is incomplete. Does this improve it? https://github.com/helm/helm-www/pull/1071/files - thanks.

**Comment by rcousineau-xandr** [comment]
Yes thank you. Do those generated files get committed in this helm-www repo, though?

They should be put into `content/en/docs/helm/` in this repo, right? I tried it and ran into a lot of changes like this:

```diff
-      --registry-config string      path to the registry config file (default "~/.config/helm/registry.json")
+      --registry-config string      path to the registry config file (default "/Users/rcousineau/Library/Preferences/helm/registry.json")
```

Is there a flag to prevent that? Or does it require lots of manual reverting to `~` in general?

**Comment by bacongobbler** [comment]
Yes. They are committed to this repository after a new Helm release. This prevents cases where a PR that is still in-flight might accidentally be merged in the docs, but the PR is later rejected or changed.

**Comment by bacongobbler** [comment]
Let's wait until helm/helm#9604 has been accepted and merged before proceeding here. Once merged the changes in that PR will be brought in with the next Helm release.

Closing for now.

**Pull request closed without merging**
